### ISSUE TITLE
Add new papers

### ISSUE THREAD

**Issue by ustctf** [D-X-Y/awesome-NAS#1]
Hi,

Would you please add our recent paper on NAS to the list? The title is [Neural Architecture Optimization ](https://arxiv.org/pdf/1808.07233.pdf), which is accepted at NIPS this year.  Maybe it can be categorized into the gradient based method.  Thanks.

Best

**Comment by D-X-Y** [comment]
Thanks a lot. I just added this paper in the list. Please let me know if you plan to release the code or have the updated results on ImageNet.

**Comment by ustctf** [comment]
Hi our code is available at https://github.com/renqianluo/NAO Thanks.
