### ISSUE TITLE
ICLR 2020 Paper

### ISSUE THREAD

**Issue by JaminFong** [D-X-Y/Awesome-NAS#12]
Hi Xuanyi,
We have a NAS related paper in ICLR 2020, 'Fast Neural Network Adaptation via Parameter Remapping and Architecture Search'. 
Paper: https://openreview.net/forum?id=rklTmyBKPH
Code: https://github.com/JaminFong/FNA
We wonder if it is OK to add this paper. Thank you!

**Comment by D-X-Y** [comment]
Nice work and congrats to your ICLR paper. I just added it.

**Comment by JaminFong** [comment]
Thank u so much!
