### ISSUE TITLE
The paper "ProxylessNAS: Direct Neural Architecture Search on Target Task and Hardware" is a gradient based method.

### ISSUE THREAD

**Issue by zhengxiawu** [D-X-Y/awesome-NAS#2]

**Comment by D-X-Y** [comment]
Thanks

**Comment by Lyken17** [comment]
umm. I am the author of ProxylessNAS. Actually, we have experimented on both RL and Gradients.

**Comment by D-X-Y** [comment]
@Lyken17 Yes, I will correct it.

**Comment by Lyken17** [comment]
By naively considering latency as (CE_loss + lambda * latency), the Gradients-based models are slightly worse than RL-based models. So our main results are from RL-based approaches.
