### ISSUE TITLE
New Paper Adding

### ISSUE THREAD

**Issue by chengaopro** [D-X-Y/Awesome-NAS#20]
Hi,

Here is our new CVPR 2020 paper "AdversarialNAS: Adversarial Neural Architecture Search for GANs"
Paper Link: https://arxiv.org/pdf/1912.02037.pdf
Code link: https://github.com/chengaopro/AdversarialNAS
Type is gradient-based.

Thx!

**Comment by D-X-Y** [comment]
Cool, added.
