### ISSUE TITLE
New Paper Adding CVPR 2020

### ISSUE THREAD

**Issue by liuzechun** [D-X-Y/Awesome-NAS#26]
Hi Xuanyi,

Thanks for making this awesome summary list!

Here is our new CVPR 2020 paper "Binarizing MobileNet via Evolution-based Searching"
Paper Link: https://arxiv.org/abs/2005.06305
Type is Evolution Algorithm.

Thanks!

**Comment by D-X-Y** [comment]
Done, you are welcome!
