### ISSUE TITLE
New paper

### ISSUE THREAD

**Issue by zym1119** [D-X-Y/awesome-NAS#4]
Hi, our new paper about nas has accepted by CVPR2019, would you please add it on your list?

Name:
Partial Order Pruning: for Best Speed/Accuracy Trade-off in Neural Architecture Search
Link:
https://arxiv.org/abs/1903.03777

**Comment by D-X-Y** [comment]
Already added in https://github.com/D-X-Y/awesome-NAS#evolutionary-algorithm
