### ISSUE TITLE
ICLR 2019 Paper

### ISSUE THREAD

**Issue by Minione** [D-X-Y/Awesome-NAS#5]
Hello,

Here is the link to our ICLR 2019 paper on automatically searching for a compressed architecture with Bayesian optimization:  https://openreview.net/forum?id=S1xLN3C9YX . Our code is also available here: https://github.com/Friedrich1006/ESNAC .

Our lab also has a ICLR 2018 paper (https://openreview.net/forum?id=B1hcZZ-AW) that uses reinforcement learning to search for compressed architectures.

Would you please add them to the list? Thanks!

**Comment by Minione** [comment]
Another paper on NAS from Google: https://arxiv.org/pdf/1802.03268.pdf .

**Comment by D-X-Y** [comment]
Thanks for your suggestion. Your ICLR 2018 and ICLR 2019 are just added. The Google paper was already in the list.
